# 服务器前置任务(ubuntu使用 Centos项目注释或删掉)
- name: Pre_awx
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes
  
# 核心任务

- name: awx
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - {role: cloud, tags: "cloud"}
    - {role: common, tags: "common"}
    - {role: docker, tags: "docker"}
    - {role: node.js, tags: "node.js"}
    - {role: awx, tags: "awx"}
    - {role: end, tags: "end"}