# 核心任务
- name: awx
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_docker, tags: "role_docker"}
    - {role: role_nodejs, tags: "role_nodejs"}
    - {role: awx, tags: "awx"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
