# 核心任务
- name: awx
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_docker, tags: "role_docker"}
    - {role: role_node.js, tags: "role_node.js"}
    - {role: awx, tags: "awx"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
