---
- name: change ansible_python_interpreter to python3
  lineinfile:
    path: "{{ awx_repo_dir }}/installer/inventory"
    regexp: 'localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"'
    line: localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ postgres_data_dir }} -e docker_compose_dir={{ docker_compose_dir }}"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete
