---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Creates awx dock directory
  file:
    path: /data/.awx/redis_socket
    state: directory
    recurse: yes

- name: Copy credentials.py
  template:
    src: credentials.py
    dest: '/data/.awx'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: '/data/.awx'

- name: Copy environment.sh
  template:
    src: environment.sh
    dest: '/data/.awx'

- name: Copy nginx.conf
  template:
    src: nginx.conf
    dest: '/data/.awx'

- name: Copy redis.conf
  template:
    src: redis.conf
    dest: '/data/.awx'

- name: Copy SECRET_KEY
  template:
    src: SECRET_KEY
    dest: '/data/.awx'

