---
- name: Create awx User
  user:
    name: awx
    shell: /usr/sbin/nologin

- name: Create awx directory
  file:
    path: /data/.awx
    state: directory
    owner: awx
    group: awx
    recurse: yes

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: awx_docker_gateway

- name: Copy docker env
  template:
    src: "{{item}}"
    dest: '/data/.awx'
  loop:
    - credentials.py
    - docker-compose.yml
    - environment.sh
    - nginx.conf
    - redis.conf
    - SECRET_KEY
    
- name: Create awx soft link to /data/wwwroot/awx
  file:
    src: /data/.awx
    dest: /data/wwwroot/awx
    state: link
    
- name: Run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data/.awx
